language: objective-c
osx_image: xcode7.2
notifications:
  email: false
  campfire:
    on_success: always
    on_failure: always
    rooms:
    - secure: "QVVzkmaWyLgGMOgtaBF2EUQS3Ot1Bj7jc8CI7L1mqxrDpNnxtemgSNBkvFNrec0RoSMiHBY9t+aVdnHsCLlqhDs3mX55zxlbTJPDpFTVI2p77n90teuOr1kK+a3DYoyaxO6acrAJwhjOe6j9zd3o/su+VG5OsXqCXhBFfnc863w="
script:
- xcodebuild -scheme 'Mantle Mac' test
- xcodebuild -scheme 'Mantle iOS' -sdk iphonesimulator test
- xcodebuild -scheme 'Mantle watchOS' build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
